2012-11-21 16:32:04

2012-11-21 16:34:50		120+46=166


2012-11-21 16:32:05

2012-11-21 16:41:37		9*60+32=540+32=572


order_on	2012-11-21 18:49:19	2012-11-21 19:41:05
order			2012-11-21 18:49:19	2012-11-21 23:54:11

select count(0) from umpay.t_up_order_on;
select count(0) from umpay.t_up_order_ext_on;
select count(0) from umpay.t_up_trans_on;

select count(0) from umpay.t_up_order;
select count(0) from umpay.t_up_order_ext;
select count(0) from umpay.t_up_trans;

select count(0) from umpay.t_up_db_syn_opt;

select intime,t.* from umpay.t_up_order_on t order by intime desc fetch first 1 rows only;
select intime,t.* from umpay.t_up_order_on t order by intime asc fetch first 1 rows only;

select intime,t.* from umpay.t_up_order t order by intime desc fetch first 1 rows only;
select intime,t.* from umpay.t_up_order t order by intime asc fetch first 1 rows only;

select * from umpay.t_up_db_syn_opt order by optid asc;

select h.* from umpay.t_up_db_syn_opt h order by h.optId asc fetch first 1 rows only;


delete from umpay.t_up_db_syn_opt;
delete from umpay.t_up_order_on;
delete from umpay.t_up_order;
delete from umpay.t_up_order_ext;
delete from umpay.t_up_order_ext_on;
delete from umpay.t_up_trans;
delete from umpay.t_up_trans_on;
delete from umpay.jms_messages;

================================================================================================
DROP TABLE UMPAY.T_UP_ORDER;
CREATE
    TABLE UMPAY.T_UP_ORDER
    (
        TRADENO CHARACTER(16) DEFAULT '' NOT NULL,
        ORDERID CHARACTER(32) DEFAULT '' NOT NULL,
        ORDERDATE CHARACTER(8) DEFAULT '' NOT NULL,
        MERID CHARACTER(16) DEFAULT '' NOT NULL,
        SUBMERID CHARACTER(16) DEFAULT '' NOT NULL,
        MEDIATYPE CHARACTER(16) DEFAULT '' NOT NULL,
        MEDIANO CHARACTER(64) DEFAULT '' NOT NULL,
        EXPIRETIME TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL,
        BANKTYPE SMALLINT DEFAULT 0 NOT NULL,
        BANKID CHARACTER(8) DEFAULT '' NOT NULL,
        ACCOUNTTYPE CHARACTER(2) DEFAULT '01' NOT NULL,
        ORDERSTATE SMALLINT DEFAULT 0 NOT NULL,
        ACCESSTYPE CHARACTER(2) DEFAULT 'w' NOT NULL,
        ISNEW SMALLINT DEFAULT 0 NOT NULL,
        GOODSID CHARACTER(8) DEFAULT '' NOT NULL,
        GOODSINFO VARCHAR(128) DEFAULT '' NOT NULL,
        AMOUNT DECIMAL(13,0) DEFAULT 0 NOT NULL,
        ORIGAMT DECIMAL(13,0) DEFAULT 0 NOT NULL,
        AMTTYPE CHARACTER(2) DEFAULT '01' NOT NULL,
        REFUNDTIMES SMALLINT DEFAULT 0 NOT NULL,
        REFUNDAMT DECIMAL(13,0) DEFAULT 0 NOT NULL,
        PAYCOUNT SMALLINT DEFAULT 0 NOT NULL,
        USERIP CHARACTER(16) DEFAULT '' NOT NULL,
        INTIME TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL,
        MODTIME TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL,
        PRIMARY KEY (TRADENO)
    );

DROP TABLE UMPAY.T_UP_ORDER_EXT;
CREATE
    TABLE UMPAY.T_UP_ORDER_EXT
    (
        TRADENO CHARACTER(16) DEFAULT '' NOT NULL,
        RETURL VARCHAR(128) DEFAULT '' NOT NULL,
        NOTIFYURL VARCHAR(128) DEFAULT '' NOT NULL,
        INTIME TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL,
        PRIMARY KEY (TRADENO)
    );

DROP TABLE UMPAY.T_UP_ORDER_EXT_ON;
CREATE
    TABLE UMPAY.T_UP_ORDER_EXT_ON
    (
        TRADENO CHARACTER(16) DEFAULT '' NOT NULL,
        RETURL VARCHAR(128) DEFAULT '' NOT NULL,
        NOTIFYURL VARCHAR(128) DEFAULT '' NOT NULL,
        INTIME TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL,
        PRIMARY KEY (TRADENO)
    );

DROP TABLE UMPAY.T_UP_ORDER_ON;
CREATE
    TABLE UMPAY.T_UP_ORDER_ON
    (
        TRADENO CHARACTER(16) DEFAULT '' NOT NULL,
        ORDERID CHARACTER(32) DEFAULT '' NOT NULL,
        ORDERDATE CHARACTER(8) DEFAULT '' NOT NULL,
        MERID CHARACTER(16) DEFAULT '' NOT NULL,
        SUBMERID CHARACTER(16) DEFAULT '' NOT NULL,
        MEDIATYPE CHARACTER(16) DEFAULT '' NOT NULL,
        MEDIANO CHARACTER(64) DEFAULT '' NOT NULL,
        EXPIRETIME TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL,
        BANKTYPE SMALLINT DEFAULT 0 NOT NULL,
        BANKID CHARACTER(8) DEFAULT '' NOT NULL,
        ACCOUNTTYPE CHARACTER(2) DEFAULT '01' NOT NULL,
        ORDERSTATE SMALLINT DEFAULT 0 NOT NULL,
        ACCESSTYPE CHARACTER(2) DEFAULT 'w' NOT NULL,
        ISNEW SMALLINT DEFAULT 0 NOT NULL,
        GOODSID CHARACTER(8) DEFAULT '' NOT NULL,
        GOODSINFO VARCHAR(128) DEFAULT '' NOT NULL,
        AMOUNT DECIMAL(13,0) DEFAULT 0 NOT NULL,
        ORIGAMT DECIMAL(13,0) DEFAULT 0 NOT NULL,
        AMTTYPE CHARACTER(2) DEFAULT '01' NOT NULL,
        REFUNDTIMES SMALLINT DEFAULT 0 NOT NULL,
        REFUNDAMT DECIMAL(13,0) DEFAULT 0 NOT NULL,
        PAYCOUNT SMALLINT DEFAULT 0 NOT NULL,
        USERIP CHARACTER(16) DEFAULT '' NOT NULL,
        INTIME TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL,
        MODTIME TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL,
        PRIMARY KEY (TRADENO)
    );

DROP TABLE UMPAY.T_UP_TRANS;
CREATE
    TABLE UMPAY.T_UP_TRANS
    (
        TRACE CHARACTER(16) DEFAULT '' NOT NULL,
        PLATDATE CHARACTER(8) DEFAULT '' NOT NULL,
        PLATTIME CHARACTER(6) DEFAULT '' NOT NULL,
        TRADENO CHARACTER(16) DEFAULT '' NOT NULL,
        FUNCODE CHARACTER(4) DEFAULT '' NOT NULL,
        SERVTYPE CHARACTER(2) DEFAULT '' NOT NULL,
        ORDERID CHARACTER(32) DEFAULT '' NOT NULL,
        ORDERDATE CHARACTER(8) DEFAULT '' NOT NULL,
        MERID CHARACTER(16) DEFAULT '' NOT NULL,
        SUBMERID CHARACTER(16) DEFAULT '' NOT NULL,
        GOODSID CHARACTER(8) DEFAULT '' NOT NULL,
        USERID CHARACTER(16) DEFAULT '' NOT NULL,
        MEDIATYPE CHARACTER(16) DEFAULT '' NOT NULL,
        MEDIANO CHARACTER(64) DEFAULT '' NOT NULL,
        BANKTYPE SMALLINT DEFAULT 0 NOT NULL,
        BANKID CHARACTER(8) DEFAULT '' NOT NULL,
        GATEID CHARACTER(8) DEFAULT '' NOT NULL,
        ACCOUNTTYPE CHARACTER(2) DEFAULT '01' NOT NULL,
        TRANSTATE SMALLINT DEFAULT 0 NOT NULL,
        ISREVOCATION SMALLINT DEFAULT 0 NOT NULL,
        ORIGAMT DECIMAL(13,0) DEFAULT 0 NOT NULL,
        AMOUNT DECIMAL(13,0) DEFAULT 0 NOT NULL,
        AMTTYPE CHARACTER(2) DEFAULT '01' NOT NULL,
        MERSTLDATE CHARACTER(8) DEFAULT '' NOT NULL,
        MERCHECK SMALLINT DEFAULT 0 NOT NULL,
        STLDATE CHARACTER(8) DEFAULT '' NOT NULL,
        STLCHECK SMALLINT DEFAULT 0 NOT NULL,
        ORIGTRACE CHARACTER(16) DEFAULT '' NOT NULL,
        PAYCOUNT SMALLINT DEFAULT 0 NOT NULL,
        ISREPLENISH SMALLINT DEFAULT 0 NOT NULL,
        INTIME TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL,
        MODTIME TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL,
        PRIMARY KEY (TRACE)
    );

DROP TABLE UMPAY.T_UP_TRANS_ON;
CREATE
    TABLE UMPAY.T_UP_TRANS_ON
    (
        TRACE CHARACTER(16) DEFAULT '' NOT NULL,
        PLATDATE CHARACTER(8) DEFAULT '' NOT NULL,
        PLATTIME CHARACTER(6) DEFAULT '' NOT NULL,
        TRADENO CHARACTER(16) DEFAULT '' NOT NULL,
        FUNCODE CHARACTER(4) DEFAULT '' NOT NULL,
        SERVTYPE CHARACTER(2) DEFAULT '' NOT NULL,
        ORDERID CHARACTER(32) DEFAULT '' NOT NULL,
        ORDERDATE CHARACTER(8) DEFAULT '' NOT NULL,
        MERID CHARACTER(16) DEFAULT '' NOT NULL,
        SUBMERID CHARACTER(16) DEFAULT '' NOT NULL,
        GOODSID CHARACTER(8) DEFAULT '' NOT NULL,
        USERID CHARACTER(16) DEFAULT '' NOT NULL,
        MEDIATYPE CHARACTER(16) DEFAULT '' NOT NULL,
        MEDIANO CHARACTER(64) DEFAULT '' NOT NULL,
        BANKTYPE SMALLINT DEFAULT 0 NOT NULL,
        BANKID CHARACTER(8) DEFAULT '' NOT NULL,
        GATEID CHARACTER(8) DEFAULT '' NOT NULL,
        ACCOUNTTYPE CHARACTER(2) DEFAULT '01' NOT NULL,
        TRANSTATE SMALLINT DEFAULT 0 NOT NULL,
        ISREVOCATION SMALLINT DEFAULT 0 NOT NULL,
        ORIGAMT DECIMAL(13,0) DEFAULT 0 NOT NULL,
        AMOUNT DECIMAL(13,0) DEFAULT 0 NOT NULL,
        AMTTYPE CHARACTER(2) DEFAULT '01' NOT NULL,
        MERSTLDATE CHARACTER(8) DEFAULT '' NOT NULL,
        MERCHECK SMALLINT DEFAULT 0 NOT NULL,
        STLDATE CHARACTER(8) DEFAULT '' NOT NULL,
        STLCHECK SMALLINT DEFAULT 0 NOT NULL,
        ORIGTRACE CHARACTER(16) DEFAULT '' NOT NULL,
        PAYCOUNT SMALLINT DEFAULT 0 NOT NULL,
        ISREPLENISH SMALLINT DEFAULT 0 NOT NULL,
        INTIME TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL,
        MODTIME TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL,
        PRIMARY KEY (TRACE)
    );


DROP TABLE UMPAY.T_UP_DB_SYN_OPT;
CREATE
    TABLE UMPAY.T_UP_DB_SYN_OPT
    (
        OPTID BIGINT DEFAULT 0 NOT NULL,
        OPTTYPE SMALLINT DEFAULT 1 NOT NULL,
        OPTTARGET VARCHAR(32) DEFAULT '' NOT NULL,
        ENTITYTYPE VARCHAR(128) DEFAULT '' NOT NULL,
        OPTVALUE BLOB(1048576) DEFAULT NULL,
        PRIMARY KEY (OPTID)
    );
